### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by ghost** [CRASHFORT/SourceToolAssist#1]
**Is there a reason you use FindSendPropOffs over FindSendPropInfo?**
The deprecation warnings when compiling in 1.8 are quite annoying.

**Why not auto-generate folders for zones and replays in sourcemod/data/?**
I'm sure documentation is coming but I think it's best to automate as much of the installation process as possible.

**There's also some "weird" things that happen when trying to load zones or replays that don't exist.**
![1](https://cloud.githubusercontent.com/assets/22212731/18547933/f075506c-7b3d-11e6-84b1-327171d7a6ac.png)
![2](https://cloud.githubusercontent.com/assets/22212731/18547956/12883908-7b3e-11e6-83f9-60efe1a95ab6.png)

**Whenever a player finishes (atleast on lan) the server's hostname goes in the place of the player's name.**
![3](https://cloud.githubusercontent.com/assets/22212731/18548150/48863eaa-7b3f-11e6-955c-22a97f39befc.png)

**Also, there's an extra tab on the end of this line.**
https://github.com/CRASHFORT/SourceToolAssist/blob/76788ac562f08b5c90d3bdf48885c0ecdb6fd265/Source/STA/Offsets.inc#L35

Other than these small nitpicky issues this is amazing, I've been waiting since you released the original video almost 2 months ago now. I'll be using it a lot over the coming weeks, best of luck with the project.

**Comment by crashfort** [comment]
**Is there a reason you use FindSendPropOffs over FindSendPropInfo?**
Not really I guess, this is my first time using SP and things may not be done the best way, I have addressed this now.

**Why not auto-generate folders for zones and replays in sourcemod/data/?**
Yeah, now when I think about it this is how it should be done. I shouldn't store my own directory structure in the server root. I can make the structure create itself.

**There's also some "weird" things that happen when trying to load zones or replays that don't exist.**
Thank you, I have fixed this issue.

**Whenever a player finishes (atleast on lan) the server's hostname goes in the place of the player's name.**
Thank you, it is fixed now. Although I have only tested this on a standalone local SRCDS server, not an insecure listen server.

**Comment by ghost** [comment]
@CRASHFORT would you consider switching from More Colors to [ColorVariables](https://forums.alliedmods.net/showthread.php?t=267743) or [MultiColors](https://forums.alliedmods.net/showthread.php?t=247770), it's one of the only things stopping pretty much out of the box CS:GO support.

Also the only problem with the plugin I've encountered so far is the fact that zones and runs aren't loading, the saving part works fine but if I try to use the menu to load zones it simply closes. There are no error logs at all and nothing out of the ordinary in the server console at the time.

**Comment by crashfort** [comment]
I could, but I can't test development on games other than CSS.

The second issue must related to ReadDirEntry [here](https://github.com/CRASHFORT/SourceToolAssist/blob/7a73974ebbf5e2ea613eed51790f284861faf142/Source/STA/Checkpoints.inc?ts=4#L572) and [here](https://github.com/CRASHFORT/SourceToolAssist/blob/7a73974ebbf5e2ea613eed51790f284861faf142/Source/surf_segmentplay.sp?ts=4#L266). I'd have to know more about your configuration.

**Comment by ghost** [comment]
I'm not really sure what you mean by configuration sorry. I have the folder structure created at the root of the server, if I load up a map and place down zones the zones work fine for that session, I usually save them at this point aswell and get the standard chat message that they were saved. If I then load up the same map any time after this no zones automatically load and if I open the zone edit menu and try to use the override option the menu simply closes.

**Comment by crashfort** [comment]
No zones are loaded automatically as you can have multiple. Do you have permission to the directory it creates?

**Comment by strafe** [comment]
@crashfort this can be closed now, I deleted my other account so I can't.
